[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
authors = [
   { name = "Erik Thiede", email = "eht45@cornell.edu"},
]
name = "vector_playground"
version = "0.0.1"
dependencies = [
]
